### ISSUE TITLE
update redux to react-redux to import Provider from react-redux

### ISSUE THREAD

**Issue by laurkim** [learn-co-curriculum/redux-thunk-readme#12]
In the code example to incorporate middleware in the index.js file, it says: 

`import { Provider } from 'redux' `

Should be 'react-redux' instead.

**Comment by dtow55** [comment]
"We can using something like JavaScript's native Fetch API to sent a web request:"

should be

"We can USE something like JavaScript's native Fetch API to SEND a web request:"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
