### ISSUE TITLE
Please Explain Why, instead jumping to large complex solutions we didn't know we needed

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/redux-thunk-readme#13]
>We Need Middleware!
>So we need a way to dispatch an action saying we are loading data, then to make a request to the API, and then to wait for the response and then dispatch another action with the response data.
>
>Lucky for us, we can use some middleware for exactly that!
  -- said no one

### Please explain why?

The logical conclusion for how to fetch data and add it to the store is not to use middleware, it's to fetch the data and then dispatch an action to the store with the data.

### The same thing with redux in general

The logical conclusion for managing global state is to have a global state object that has methods for updating the state and provides a subscription service for getting notified of changes to state (that can be scoped to specific pieces of data).
- Why actions?
- Why reducers?
- Why dispatch?
- Why a double higher connect function? (a function that returns a function that returns a function/Component)
- Why mapDispatchToProps?

**Comment by maxwellbenton** [comment]
Hi @arye-dov-eidelman,

Thank you for this feedback. We've updated this lesson's introduction to include a better explanation as to why we might use Thunk which happens to tie into why we use Redux in general. This should help explain the purposes of using Redux with Thunk and resolve this issue.

Thank you for all of your contributions!
