### ISSUE TITLE
Multiple missing or misspelled words

### ISSUE THREAD

**Issue by mokolita** [learn-co-curriculum/redux-thunk-readme#14]
This lesson was frustrating to read through because of all the spelling or missing word errors.

**Comment by Sdcrouse** [comment]
Good news! They fixed a whole bunch of those typos a couple of months ago.

**Comment by lizbur10** [comment]
Hi there! Apologies for any frustration you experienced as a result of the errors. As Steven pointed out, the lesson has since been updated and corrections made so I'm going to close this issue. Thanks for the feedback!
