### ISSUE TITLE
Redux Thunk ReadME typos

### ISSUE THREAD

**Issue by glotzbachs** [learn-co-curriculum/redux-thunk-readme#15]
Last sentence of first intro paragraph: **A** of code that would normally be stored in React components can be removed or replaced.
Not sure what you meant. All of the code? A lot of code? A piece of code?

Second Intro Paragraph:  So far, it's all **be** hard-coded data, i.e. data that we set ourselves. 
It's all been?..

Second section title: Trying to **Sent** an Asynchronous Request in Redux
Trying to Send?..

**Comment by Sdcrouse** [comment]
It looks like these typos have been fixed.

**Comment by lizbur10** [comment]
Hello! As Steven pointed out, the typos you spotted have been fixed so I'm going to resolve this issue. Thanks for providing feedback!
